### ISSUE TITLE
Patching error installing with Composer on Windows

### ISSUE THREAD

**Issue by Nick-Hopps** [acquia/lightning-project#115]
The same as #113, im using git bash and xampp on my windows 10

**Comment by penance316** [comment]
Same issue here. Did you ever get a fix or workaround for this ?

**Comment by Nick-Hopps** [comment]
> 
> 
> Same issue here. Did you ever get a fix or workaround for this ?

just give up windows. I'm now using wsl2

**Comment by penance316** [comment]
> > Same issue here. Did you ever get a fix or workaround for this ?
> 
> just give up windows. I'm now using wsl2
Thanks,
I have been starting to use WSL2 myself and seems like the best approach now.
