### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Timoti** [acquia/lightning-project#12]
I've attempted a composer install with no success

> zsh: composer create-project acquia/lightning-project:^8.1.0 MY_PROJECT --no-interaction

results in

> zsh: no matches found: acquia/lightning-project:^8.1.0

I am composer --version 1.1.1, node --version 5.4.0

anything I should look for?
(in the meantime using the depreciated old school sip DL method - anything I will miss out on with that?)

**Comment by balsama** [comment]
Other than composer cache, I can't think of anything. The package definitely exists:
https://packagist.org/packages/acquia/lightning-project#8.1.0

Try clearing your composer cache first I guess:

    composer clear-cache

The only other thing I can think of is a global composer setting you have that is looking for the package at a different packagist.

**Comment by ashlewis** [comment]
I had the same issue. Adding quotes around package works for me:
`composer create-project "acquia/lightning-project:^8.1.0" MY_PROJECT --no-interaction`

**Comment by balsama** [comment]
huh. Is that related to `zsh`? Is that a known issue (or difference)?

**Comment by Timoti** [comment]
Yes quotes fixed it for me in zsch  - thanks!
