### ISSUE TITLE
Upgrade Issues

### ISSUE THREAD

**Issue by albertski** [acquia/lightning-project#13]
When upgrading Lighting from one version to next I am running into problems because of requirements.  To get around this I just delete the composer.lock file and rerun composer install.  Is that the correct way to do it?

Here is what happens if I upgrade from Lightning 8.1.00-rc6 to 8.1.0.

```
± |master ✓| → composer require drupal/lightning:8.1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
    1/1:  http://packagist.org/p/provider-latest$aa4f1da6acef0b15640bc1cace21327f5342dbb88c61b4605f0b1b0ff21d7399.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: drupal/entity_browser[8.1.x-dev, 8.1.0-alpha3].
    - Can only install one of: drupal/entity_browser[8.1.0-alpha3, 8.1.x-dev].
    - drupal/lightning 8.1.00 requires drupal/entity_browser 8.1.0-alpha3 -> satisfiable by drupal/entity_browser[8.1.0-alpha3].
    - Installation request for drupal/lightning 8.1.0 -> satisfiable by drupal/lightning[8.1.00].
    - Installation request for drupal/entity_browser (locked at 8.1.x-dev) -> satisfiable by drupal/entity_browser[8.1.x-dev].


Installation failed, reverting ./composer.json to its original content.
```

Is there a way to upgrade without deleting the composer.lock file or is that what I should be doing every time I upgrade?

**Comment by balsama** [comment]
Deleting the composer.lock file and running composer install is fine. But I think you're looking for the composer update command. Composer install does run composer update if the lock file is missing. But composer update will update your existing lock file. See "Install or Update" section here: https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file

**Comment by albertski** [comment]
Thanks @balsama  The weird thing is that composer update does not update lightning.

composer.json:
```
.....
"drupal/lightning": "8.1.*",
.....
```

composer.lock:
```
.....
{
            "name": "drupal/lightning",
            "version": "8.1.00-rc5",
            "source": {
                "type": "git",
                "url": "https://git.drupal.org/project/lightning.git",
                "reference": "04f5c05d03dfbb9354f72cf62a98ac2a3275bb74"
            },
            "dist": {
                "type": "zip",
                "url": "https://ftp.drupal.org/files/projects/lightning-8.x-1.00-rc5.zip",
                "reference": "04f5c05d03dfbb9354f72cf62a98ac2a3275bb74",
                "shasum": null
            },
.....
```

If I run `composer update` or `composer update drupal/lightning` it does not update it.

The only way I can get it to update is if delete comoser.lock.

**Comment by balsama** [comment]
Looks like you have a conflict with something in your project and composer is resolving that by degrading to lightning beta5. Try merging the latest requirements from lightning project into your project. E.g:

'''
        "composer/installers": "^1.0",
        "drupal-composer/drupal-scaffold": "^2.0.0",
        "cweagans/composer-patches": "1.5.0",
        "drupal/lightning": "^8.1.0"
'''

**Comment by albertski** [comment]
@baliame Sorry I was actually upgrading from rc5 to 8.1.0.  Updating the composer manually and running update worked.

So down the road if you guys release 8.2.0 I will need to update lightning as specified above?

Thanks for you help!

FYI here are my files at rc5:
composer.json: http://pasted.co/f2561b5d
composer.lock: http://pasted.co/573a945e

**Comment by baliame** [comment]
Hi,  you somehow managed to tag me instead of that dude. I got highly confused.

**Comment by albertski** [comment]
I believe the issue was related that I didn't have the `^` for drupal/lightning (like @balsama pointed out).

I think going forward I shouldn't run into any issues. (Didn't test from RC to 8.1.x but I didn't run into any issues lately).
