### ISSUE TITLE
Consider using https://packages.drupal.org/8

### ISSUE THREAD

**Issue by greg-1-anderson** [acquia/lightning-project#22]
Any reason you're still on https://packagist.drupal-composer.org?  drupal-composer/drupal-project is now using the [official packagist repository on drupal.org](https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies).

One thing I noticed when trying to switch over is that packagist.drupal.org seems to put the entire Drupal distribution in profiles/lighting.  ~Perhaps this could be resolved by requiring [acquia/lightning](https://packagist.org/packages/acquia/lightning-project) directly?~

**Comment by greg-1-anderson** [comment]
Ah, I see. At the time of this writing, [Using packages.drupal.org](https://www.drupal.org/docs/develop/using-composer/using-packagesdrupalorg) says "Distributions and install profiles are not yet supported."

**Comment by balsama** [comment]
See this comment for the latest on this. https://www.drupal.org/node/2728777#comment-11789541

We're considering submitting lightning itself to the main packagist as a workaround.
