### ISSUE TITLE
Installer path for drupal/core missing type

### ISSUE THREAD

**Issue by jmolivas** [acquia/lightning-project#23]
Any reason why te installer path for `drupal/core`  is missing the `type`

Actual value:
```
            "docroot/core": [
                "drupal/core"
            ],
```
Instead of:
```
            "docroot/core": [
                "type:drupal-core"
            ],
```

You can see it at the `composer.json` file at 
https://github.com/acquia/lightning-project/blob/8.x/composer.json#L52-L54

**Comment by balsama** [comment]
I'm actually not sure why. Tests seem to pass after changing it. We have the same thing in lightning itself too.

Just so I understand, do you think this was causing problems? If so, can you describe how?

**Comment by jmolivas** [comment]
I dot no see any problems other than issues with the `drupal-finder` https://github.com/webflo/drupal-finder/pull/11 that got fixed already 

But that definition doe not look correct, that is why I reported by creating an issue.

**Comment by balsama** [comment]
This was updated in da24a73c621df16fcd13c779b35c238b65419b76. Thanks!
