### ISSUE TITLE
composer & acquia cloud 

### ISSUE THREAD

**Issue by davidgil** [acquia/lightning-project#4]
Hi!,

One question with new composer style of making sites. sure you can help me and others working as you do in acquia. the question is how do you deploy this kind of distros in platforms like acquia cloud if you exclude vendor folders from GIT. Any clue is welcome! 

thx in advance

**Comment by phenaproxima** [comment]
CC'ing @erikwebb.

**Comment by erikwebb** [comment]
@davidgil We are currently looking into the best methods to install and updated D8-specific tools (e.g. Composer, Drupal Console). We are also planning out for new ways to build and deploy Drupal projects, differently than our current Git-specific workflow.

**Comment by davidgil** [comment]
thx @erikwebb, but nowadays, what do you do as workaround?, include vendor folders in GIT?

**Comment by erikwebb** [comment]
@davidgil Currently, yes. Artifact-based deployments are in active development and absolutely our long-term plan.

**Comment by benedikt-d** [comment]
Has anything changed in that space?

**Comment by balsama** [comment]
@benedikt-d lots. Checkout https://docs.acquia.com/pipelines and/or https://github.com/acquia/blt
