### ISSUE TITLE
Ad Update info in project Readme

### ISSUE THREAD

**Issue by marceldobrica** [acquia/lightning-project#46]
Please add info about update. 
I wasn't able to update the project from 2.18 to 2.20 without changing composer.json file and I believe it have to be mentioned.

**Comment by balsama** [comment]
What did you have to change in your composer.json file?

**Comment by marceldobrica** [comment]
In old version was 
"require": {
        "drupal-composer/drupal-scaffold": "^2.0.0",
        "cweagans/composer-patches": "^1.6.0",
        "acquia/lightning": "~2.1.8"
    },
In fact I have completely replaced old composer.json with the new one from the repository and then issue the command "composer update". I believe it has to be mentioned.
In fact even now on composer.json we have 
"require": {
        "drupal-composer/drupal-scaffold": "^2.0.0",
        "cweagans/composer-patches": "^1.6.0",
        "acquia/lightning": "~2.2.0",
        "drupal/core": "~8.4.0"
    }, so next update to acquia/lightning 2.3.0, simply with composer update command will not work without changing composer.json file.
