### ISSUE TITLE
create project not working

### ISSUE THREAD

**Issue by davidgil** [acquia/lightning-project#5]
Hi,

In the doc you have a small problem, if you use:

composer create-project acquia/lightning-project:dev-master MY_PROJECT --no-interaction

I think the right command is now:

composer create-project acquia/lightning-project:8.x-dev MY_PROJECT --no-interaction

Best
David

**Comment by balsama** [comment]
Yes, I think you're correct. We're tagging our RC1 today and announcing on Monday. All of the references in the docs will be updated (and maintained) after that. Thanks!
