### ISSUE TITLE
Proper upgrade from from 2.2.7 to 3.0.0?

### ISSUE THREAD

**Issue by marceldobrica** [acquia/lightning-project#61]
What is the process to upgrade composer lightning project from acquia/lightning (2.2.7) to acquia/lightning (3.0.0) - simple composer update and drush updb dosen't work.

**Comment by balsama** [comment]
Hi. You need to change the constraint in your composer.json file. You can do so by running the following commands:

```
composer require acquia/lightning:~3.0.1 --no-update
composer update
```

**Comment by marceldobrica** [comment]
Thank you.
