### ISSUE TITLE
Error : Repository type is not registered: github

### ISSUE THREAD

**Issue by clauded** [acquia/lightning-project#67]
I'm trying to install Drupal/lightning with composer but I get the following error:
```
[InvalidArgumentException]                 
Repository type is not registered: github
```
In composer.json, the dev repo is of type "github":
```
 "dev": {
            "type": "github",
            "url": "https://github.com/acquia/lightning-dev",
            "no-api": true
        }
```

**Comment by clauded** [comment]
The version that comes with Ubuntu 16.04:

Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34

**Comment by phenaproxima** [comment]
Ah, OK. That's very out of date; the current version of Composer is something like 1.6.x. It's quite possible that the github driver was introduced after 1.0.0, so I suggest updating to the latest version of Composer and trying again.

**Comment by clauded** [comment]
Ok. Got it working by removing the one from the distribution and installing manually a recent version. For reference if someone else encounter the error:
```
sudo apt install -y git unzip curl php-mbstring php-cli
curl -sS https://getcomposer.org/installer -o composer-setup.php
sudo php composer-setup.php --install-dir=/usr/bin --filename=composer
```
Thanks for the help.

**Comment by phenaproxima** [comment]
You're quite welcome. Glad you got it working :)

**Comment by balsama** [comment]
Related: #68
