### ISSUE TITLE
 I'm trying to give command in SSH and came across this message

### ISSUE THREAD

**Issue by matheusgabriel10** [acquia/lightning-project#69]
Warning: require(/home/logim619/vendor/composer/../magento/language-pt_br/registration.php): failed to open stream: No such file or directory in /home/logim619/vendor/composer/autoload_real.php on line 70

Fatal error: require(): Failed opening required '/home/logim619/vendor/composer/../magento/language-pt_br/registration.php' (include_path='/home/logim619/vendor/magento/zendframework1/library:.:/opt/php71/lib/php') in /home/logim619/vendor/composer/autoload_real.php on line 70

**Comment by balsama** [comment]
Hi. It looks like one of your dependencies is missing (that was presumably there when you generated your autoload file). Perhaps running `composer update` will fix it?

**Comment by matheusgabriel10** [comment]
como faço isso sou leigo totalmente no assunto ?

**Comment by matheusgabriel10** [comment]
oque devo fazer aqui estou na linha 70 


function composerRequire9b6fc3d821a4214f4eb6c6288331e61d($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}

**Comment by matheusgabriel10** [comment]
function composerRequire9b6fc3d821a4214f4eb6c6288331e61d($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}

**Comment by matheusgabriel10** [comment]
oque devo fazer ?

**Comment by matheusgabriel10** [comment]
esse é o erro que me aparece aqui em baixo 


Warning: require(/home/logim619/vendor/composer/../magento/language-pt_br/registration.php): failed to open stream: No such file or directory in /home/logim619/vendor/composer/autoload_real.php on line 70

Warning: require(/home/logim619/vendor/composer/../magento/language-pt_br/registration.php): failed to open stream: No such file or directory in /home/logim619/vendor/composer/autoload_real.php on line 70

Fatal error: require(): Failed opening required '/home/logim619/vendor/composer/../magento/language-pt_br/registration.php' (include_path='/home/logim619/vendor/magento/zendframework1/library:.:/opt/php70/lib/php') in /home/logim619/vendor/composer/autoload_real.php on line 70

**Comment by matheusgabriel10** [comment]
cmo posso consertar ?

2018-03-26 12:38 GMT-03:00 Adam Balsam <notifications@github.com>:

**Comment by phenaproxima** [comment]
I don't think this problem is necessarily related to Lightning Project. Based on the error messages you posted, it looks like this might be more related to something in Magento. I would recommend continuing to pursue this issue with them, as I'm not sure how we can be of help. So I'm closing this issue.

**Comment by matheusgabriel10** [comment]
Olá,

Eu acabei de assinar o abaixo-assinado "Presidente da Câmara Rodrigo Maia:
PELO FIM DO FORO PRIVILEGIADO JÁ" e queria saber se você pode ajudar
assinando também.

A nossa meta é conseguir 1.000 assinaturas e precisamos de mais apoio. Você
pode ler mais sobre este assunto e assinar o abaixo-assinado aqui:

http://chng.it/KztcDDhPhx

Obrigado!
matheus gabriel
