### ISSUE TITLE
Composer install fails to load the libraries

### ISSUE THREAD

**Issue by wroxbox** [acquia/lightning-project#7]
All these libraries were not installed by composer install. Wonder why?

libraries[backbone.collectionView][type] = library
libraries[backbone.collectionView][directory_name] = backbone.collectionView
libraries[backbone.collectionView][download][type] = git
libraries[backbone.collectionView][download][url] = git://github.com/rotundasoftware/backbone.collectionView.git
libraries[backbone.collectionView][download][tag] = v1.0.6
libraries[dropzone][type] = library
libraries[dropzone][directory_name] = dropzone
libraries[dropzone][download][type] = git
libraries[dropzone][download][url] = git://github.com/enyo/dropzone.git
libraries[dropzone][download][tag] = v4.3.0
libraries[es6-promise][type] = library
libraries[es6-promise][directory_name] = es6-promise
libraries[es6-promise][download][type] = git
libraries[es6-promise][download][url] = https://github.com/jakearchibald/es6-promise.git
libraries[es6-promise][download][tag] = v3.2.1
libraries[jquery_appear][type] = library
libraries[jquery_appear][directory_name] = jquery_appear
libraries[jquery_appear][download][type] = git
libraries[jquery_appear][download][url] = git://github.com/morr/jquery.appear.git
libraries[jquery_appear][download][tag] = 0.3.6

**Comment by balsama** [comment]
Hi. Do you have any more details? What method did you use to install? Did you see any errors? What was your resulting file structure? Do you see anything in your `MYPROJECT/docroot/profiles/contrib/libraries` folder? Does it exist at all?

**Comment by wroxbox** [comment]
I've doublechecked that I have NPM installed so ScriptHandler can DeployLibraries but running:

vagrant@drupalvm:/var/www$ composer create-project acquia/lightning-project:8.1.* lightningbuild --no-interaction --stability rc

Inside DrupalVM does not install libraries under docroot/profiles/contrib/lightning/

There are some errors like:

Writing lock file
Generating autoload files
> DrupalComposer\DrupalScaffold\Plugin::scaffold
 [FileSystem\FilesystemStack] mkdir ["\/tmp\/\/drupal-scaffold-1460008986"]
 [FileSystem\FilesystemStack] mkdir ["\/var\/www\/lightningbuild\/docroot\/sites\/default"]
 [FileSystem\FilesystemStack] _chmod ["\/var\/www\/lightningbuild\/docroot\/sites\/default",493]
 [FileSystem\CleanDir] Cleaned /tmp//drupal-scaffold-1460008986
➜  Attempt to download https://ftp.drupal.org/files/projects/drupal-8.0.6.tar.gz to /tmp//drupal-scaffold-1460008986/drupal-8.0.6.tar.gz
 [Archive\Extract] Extracting /tmp//drupal-scaffold-1460008986/drupal-8.0.6.tar.gz
 [Archive\Extract] /tmp//drupal-scaffold-1460008986/drupal-8.0.6.tar.gz extracted
 [FileSystem\FilesystemStack] _rename ["\/var\/www\/lightningbuild\/tmp1729621931460008995\/drupal-8.0.6","\/tmp\/\/drupal-scaffold-1460008986\/drupal-8"]
 [FileSystem\CopyDir] Copied from /var/www/lightningbuild/tmp1729621931460008995/drupal-8.0.6 to /tmp//drupal-scaffold-1460008986/drupal-8
 [Remote\Rsync] Running rsync -a -v -z --include 'sites' --include 'sites/default' --include 'sites/default/default.settings.php' --include 'sites/default/default.services.yml' --include 'sites/development.services.yml' --include 'sites/example.settings.local.php' --include 'sites/example.sites.php' --exclude '.gitkeep' --exclude 'autoload.php' --exclude 'composer.json' --exclude 'composer.lock' --exclude 'core' --exclude 'drush' --exclude 'example.gitignore' --exclude 'LICENSE.txt' --exclude 'README.txt' --exclude 'vendor' --exclude 'themes' --exclude 'profiles' --exclude 'modules' --exclude 'sites/*' --exclude 'sites/default/*' '/tmp//drupal-scaffold-1460008986/drupal-8/' '/var/www/lightningbuild/docroot'
sending incremental file list
rsync: chgrp "/var/www/lightningbuild/docroot/." failed: Operation not permitted (1)
./
.csslintrc
rsync: chgrp "/var/www/lightningbuild/docroot/sites" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/sites/default" failed: Operation not permitted (1)
.editorconfig
.eslintignore
.eslintrc
.gitattributes
.htaccess
index.php
robots.txt
update.php
web.config
sites/
sites/development.services.yml
sites/example.settings.local.php
sites/example.sites.php
sites/default/
sites/default/default.services.yml
sites/default/default.settings.php
rsync: chgrp "/var/www/lightningbuild/docroot/.csslintrc.XvZzVn" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.editorconfig.IKQXeP" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.eslintignore.YQxzyg" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.eslintrc.EynmSH" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.gitattributes.4Wllc9" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.htaccess.kZIxwA" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.index.php.ClnXQ1" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.robots.txt.6j6ybt" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.update.php.qGTmwU" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/.web.config.CjelRl" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/sites/.development.services.yml.57HvcN" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/sites/.example.settings.local.php.99bUxe" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/sites/.example.sites.php.m6rBTF" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/sites/default/.default.services.yml.kiMvf7" failed: Operation not permitted (1)
rsync: chgrp "/var/www/lightningbuild/docroot/sites/default/.default.settings.php.MrwCBy" failed: Operation not permitted (1)

sent 22,657 bytes  received 2,289 bytes  49,892.00 bytes/sec
total size is 60,284  speedup is 2.42
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
 [Remote\Rsync] sending incremental file list
 [Remote\Rsync] ./
 [Remote\Rsync] .csslintrc
 [Remote\Rsync] .editorconfig
 [Remote\Rsync] .eslintignore
 [Remote\Rsync] .eslintrc
 [Remote\Rsync] .gitattributes
 [Remote\Rsync] .htaccess
 [Remote\Rsync] index.php
 [Remote\Rsync] robots.txt
 [Remote\Rsync] update.php
 [Remote\Rsync] web.config
 [Remote\Rsync] sites/
 [Remote\Rsync] sites/development.services.yml
 [Remote\Rsync] sites/example.settings.local.php
 [Remote\Rsync] sites/example.sites.php
 [Remote\Rsync] sites/default/
 [Remote\Rsync] sites/default/default.services.yml
 [Remote\Rsync] sites/default/default.settings.php
 [Remote\Rsync] sent 22,657 bytes  received 2,289 bytes  49,892.00 bytes/sec
 [Remote\Rsync] total size is 60,284  speedup is 2.42
 [Remote\Rsync]  Exit code 23  Time 0.104s
 [Robo\Result] Stopping on fail. Exiting....
 [Robo\Result] Exit Code: 23


But those related only to copy drupal core into docroot (wrong permissions). The lightning installation-profile should have been installed allready before.

**Comment by balsama** [comment]
Somebody else had trouble with this running on DrupalVM. See #6 - is it possible that you're seeing the same or similar problem?

**Comment by thejimbirch** [comment]
@wroxbox Do you have npm bower installed also?  We had some library failures on computers that didn't have bower.

**Comment by blazendic** [comment]
I had similar problem on Win7 machine and installing node.js solved deploy libraries error. 
But now I'm trying same on Win8 machine and I cannot solve it. 
node -v 6.9.1
npm -v 3.10.8
composer 1.2.2
Everything same like on win7 machine but still:
http://screencast.com/t/DmQA5spdl8Gx
