### ISSUE TITLE
 I am trying to give command in SSH and I came across this message

### ISSUE THREAD

**Issue by matheusgabriel10** [acquia/lightning-project#71]
Warning: require(/home/logim619/vendor/composer/../magento/language-pt_br/registration.php): failed to open stream: No such file or directory in /home/logim619/vendor/composer/autoload_real.php on line 70

Warning: require(/home/logim619/vendor/composer/../magento/language-pt_br/registration.php): failed to open stream: No such file or directory in /home/logim619/vendor/composer/autoload_real.php on line 70

Fatal error: require(): Failed opening required '/home/logim619/vendor/composer/../magento/language-pt_br/registration.php' (include_path='/home/logim619/vendor/magento/zendframework1/library:.:/opt/php70/lib/php') in /home/logim619/vendor/composer/autoload_real.php on line 70

**Comment by phenaproxima** [comment]
Closing.
