### ISSUE TITLE
php artisan serve 

### ISSUE THREAD

**Issue by shijiezhou1** [acquia/lightning-project#77]
Warning: require(/Users/account/Sites/test/vendor/autoload.php): failed to open stream: No such file or directory in /Users/account/Sites/test/artisan on line 18

Fatal error: require(): Failed opening required '/Users/account/Sites/test/vendor/autoload.php' (include_path='.:') in /Users/account/Sites/test/artisan on line 18

I am getting this error and not able to open laravel

**Comment by phenaproxima** [comment]
This is a Drupal distribution, so we have nothing to do with Laravel :) Closing.
