### ISSUE TITLE
Include JavaScript tests in CI

### ISSUE THREAD

**Issue by balsama** [acquia/lightning-project#98]
As part of the 3.3.0 release update, I disabled Behat javascript tests because of an error with those tests that seemed unrelated to the update. See this build for an example:
https://travis-ci.org/acquia/lightning-project/jobs/527106592

Note that the failures started before the 3.3.0 release. For example:
https://travis-ci.org/acquia/lightning-project/jobs/527101071

To work around the issue, I added `--tags=~javascript` to each of the builds which excluded those tests for now.

**Comment by phenaproxima** [comment]
Fixed in 5569ee5907055c37585af028a069f1548bba590a. :)
